/** Card identities and artwork; all gameplay values come from paid/cardRules.ts. */
import type { CardMetadata } from './types.ts'

export const CARD_METADATA: readonly CardMetadata[] = [
  {"cardId": "C-01", "name": {"zh": "中国马能飞", "en": "Chinese Horses Can Fly"}, "meme": "网络梗「中国 X 能飞」", "art": {"icon": "card-1"}},
  {"cardId": "C-02", "name": {"zh": "旋转突进的蓝色小马", "en": "Spinning Blue Pony"}, "meme": "蓝色枪兵的旋转冲刺 / lancer 又死了", "art": {"icon": "card-2"}},
  {"cardId": "C-03", "name": {"zh": "最后的波纹", "en": "The Last Ripple"}, "meme": "JOJO 的波纹", "art": {"icon": "card-3"}},
  {"cardId": "C-04", "name": {"zh": "选择困难综合症", "en": "Decision Paralysis"}, "meme": "通用网络梗", "art": {"icon": "card-4"}},
  {"cardId": "C-05", "name": {"zh": "海贼王的宝藏", "en": "Pirate King's Treasure"}, "meme": "One Piece", "art": {"icon": "card-5"}},
  {"cardId": "C-06", "name": {"zh": "炸弹来咯", "en": "Bombs Away"}, "meme": "炸弹人", "art": {"icon": "card-6"}},
  {"cardId": "C-07", "name": {"zh": "火箭喷射器", "en": "Rocket Booster"}, "meme": "通用", "art": {"icon": "card-7"}},
  {"cardId": "C-08", "name": {"zh": "彩虹猫", "en": "Nyan Cat"}, "meme": "Nyan Cat", "art": {"icon": "card-8"}},
  {"cardId": "C-09", "name": {"zh": "不义游戏", "en": "Boogie Woogie"}, "meme": "咒术回战 东堂葵", "art": {"icon": "card-9"}},
  {"cardId": "C-10", "name": {"zh": "重力井", "en": "Gravity Well"}, "meme": "史瓦西黑洞", "art": {"icon": "card-10"}},
  {"cardId": "C-11", "name": {"zh": "风火轮", "en": "Wind Fire Wheels"}, "meme": "哪吒", "art": {"icon": "card-11"}},
  {"cardId": "C-12", "name": {"zh": "起风了", "en": "The Wind Rises"}, "meme": "天气预报 /「起风了」", "art": {"icon": "card-12"}},
  {"cardId": "C-13", "name": {"zh": "顺手牵羊", "en": "Sticky Fingers"}, "meme": "成语的字面直用", "art": {"icon": "card-13"}},
  {"cardId": "C-14", "name": {"zh": "望梅止渴", "en": "Quench Thirst by Watching Plums"}, "meme": "成语的字面直用", "art": {"icon": "card-14"}},
  {"cardId": "C-15", "name": {"zh": "肾上腺素", "en": "Adrenaline"}, "meme": "通用", "art": {"icon": "card-15"}},
  {"cardId": "C-16", "name": {"zh": "咖啡因过量", "en": "Caffeine Overdose"}, "meme": "熬夜 / 美式续命", "art": {"icon": "card-16"}},
  {"cardId": "C-17", "name": {"zh": "薄肌", "en": "Lean Muscle"}, "meme": "网络梗「薄肌」", "art": {"icon": "card-17"}},
  {"cardId": "C-18", "name": {"zh": "薄肌 pro max ultra", "en": "Lean Muscle Pro Max Ultra"}, "meme": "「薄肌」叠加厂商命名梗", "art": {"icon": "card-18"}},
  {"cardId": "C-19", "name": {"zh": "黄毛", "en": "Blonde"}, "meme": "通用", "art": {"icon": "card-19"}},
  {"cardId": "C-20", "name": {"zh": "我要把这玩意儿染成绿的", "en": "I'm Dyeing This Thing Green"}, "meme": "通用", "art": {"icon": "card-20"}},
  {"cardId": "C-21", "name": {"zh": "理解孙学", "en": "Enlightened"}, "meme": "网络梗「孙学」", "art": {"icon": "card-21"}},
  {"cardId": "C-22", "name": {"zh": "梭哈", "en": "All In"}, "meme": "梭哈", "art": {"icon": "card-22"}},
  {"cardId": "C-23", "name": {"zh": "摸鱼是为了更好地冲刺", "en": "Slack, Then Sprint"}, "meme": "摸鱼是为了更好地冲刺", "art": {"icon": "card-23"}},
  {"cardId": "C-24", "name": {"zh": "备用粮", "en": "Emergency Rations"}, "meme": "备用粮", "art": {"icon": "card-24"}},
  {"cardId": "C-25", "name": {"zh": "省流模式", "en": "Economy Mode"}, "meme": "省流模式", "art": {"icon": "card-25"}},
  {"cardId": "C-26", "name": {"zh": "狂暴引擎", "en": "Rage Engine"}, "meme": "狂暴引擎", "art": {"icon": "card-26"}},
  {"cardId": "C-27", "name": {"zh": "纸飞机", "en": "Paper Plane"}, "meme": "纸飞机", "art": {"icon": "card-27"}},
  {"cardId": "C-28", "name": {"zh": "接地气", "en": "Grounded"}, "meme": "接地气", "art": {"icon": "card-28"}},
  {"cardId": "C-29", "name": {"zh": "跑马灯", "en": "Coat of Many Colors"}, "meme": "跑马灯", "art": {"icon": "card-29"}},
  {"cardId": "C-30", "name": {"zh": "垃圾佬", "en": "Scrap Collector"}, "meme": "垃圾佬", "art": {"icon": "card-30"}},
  {"cardId": "C-31", "name": {"zh": "改装达人", "en": "Master Mechanic"}, "meme": "改装达人", "art": {"icon": "card-31"}},
  {"cardId": "C-32", "name": {"zh": "以旧换新", "en": "Refurbish"}, "meme": "以旧换新", "art": {"icon": "card-32"}},
  {"cardId": "C-33", "name": {"zh": "空手道", "en": "Empty Hands"}, "meme": "空手道", "art": {"icon": "card-33"}},
  {"cardId": "C-34", "name": {"zh": "年轻人不讲武德", "en": "Cheap Shot"}, "meme": "年轻人不讲武德", "art": {"icon": "card-34"}},
  {"cardId": "C-35", "name": {"zh": "赢麻了", "en": "On a Roll"}, "meme": "赢麻了", "art": {"icon": "card-35"}},
  {"cardId": "C-36", "name": {"zh": "五谷丰登", "en": "Bountiful Harvest"}, "meme": "五谷丰登", "art": {"icon": "card-36"}},
  {"cardId": "C-37", "name": {"zh": "名刀司命", "en": "Last Stand"}, "meme": "名刀司命", "art": {"icon": "card-37"}},
  {"cardId": "C-38", "name": {"zh": "嗯，来劲了", "en": "Second Wind"}, "meme": "嗯，来劲了", "art": {"icon": "card-38"}},
  {"cardId": "C-39", "name": {"zh": "躺平是种智慧", "en": "Wise Retreat"}, "meme": "躺平是种智慧", "art": {"icon": "card-39"}},
  {"cardId": "C-40", "name": {"zh": "登神长阶", "en": "Stairway to Glory"}, "meme": "登神长阶", "art": {"icon": "card-40"}},
]
