import { expect, test } from '@playwright/test'

test('the biped uses two real wheel mounts and transforms its own belly/tail anchors', async ({ page }) => {
  await page.goto('/tests/e2e/fixtures/pony-visual.html')
  await page.waitForFunction(() => 'ponyVisual' in window)
  const read = () => page.evaluate(() => (window as any).ponyVisual.snapshot())
  const idle = await read()
  expect(idle.feet).toHaveLength(2)
  expect(idle.rocket).toHaveLength(1)
  expect(idle.tail[0].x).toBeLessThan(idle.rocket[0].x)
  await page.locator('canvas').screenshot({ path: '.cache/pony-build/gugugaga-idle-equipment.png' })
  await page.evaluate(() => (window as any).ponyVisual.run())
  const running = await read()
  expect(running.texture).toBe('pony_running_8')
  expect(running.width).toBe(idle.width)
  expect(running.height).toBe(idle.height)
  await page.evaluate(() => (window as any).ponyVisual.fly())
  const flying = await read()
  expect(flying.feet[0].y).toBeCloseTo(idle.feet[0].y - 92)
  expect(flying.rocket[0].y).toBeCloseTo(idle.rocket[0].y - 92)
  await page.evaluate(() => { (window as any).ponyVisual.spin(); (window as any).ponyVisual.head() })
  const spin = await read()
  expect(spin.feet).toHaveLength(2)
  expect(spin.rocket[0].y).toBeGreaterThan(spin.feet[0].y)
  expect(spin.headVisible).toBe(true)
  await page.evaluate(() => (window as any).ponyVisual.ghost())
  const ghost = await read()
  expect(ghost.alpha).toBeGreaterThan(0)
  expect(ghost.alpha).toBeLessThan(spin.alpha)
  expect(ghost.feet).toEqual(spin.feet)
  await page.screenshot({ path: '.cache/pony-build/gugugaga-equipment.png' })
})
